[package]
name = "kaspa-merkle"
description = "Merkle tree lib"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
kaspa-hashes.workspace = true
