// Build script that precomputes empty subtree hashes for known BLAKE3 hashers.
//
// For each hasher, generates an `impl SmtHasher` block with a const array
// of 257 `Hash` values (levels 0..=256).

/// BLAKE3 hashers used for SMT internal nodes.
///
/// Each entry is `(hasher_name, domain_bytes, collapsed_hasher_name)`.
/// `collapsed_hasher_name` is the associated `CollapsedHasher` type used
/// for collapsed (single-leaf subtree) nodes in the SLO optimization.
const KNOWN_HASHERS: &[(&str, &[u8], &str)] = &[("SeqCommitActiveNode", b"SeqCommitActiveNode", "SeqCommitActiveCollapsedNode")];

const DEPTH: usize = 256;

/// Compute the 257 empty subtree hashes for a BLAKE3 keyed hasher.
///
/// Mirrors the runtime `hash_node` logic: `H(left || right)` where H is
/// `blake3::Hasher::new_keyed` with the domain string zero-padded to 32 bytes.
fn compute_empty_hashes(domain: &[u8]) -> Vec<[u8; 32]> {
    let mut key = [0u8; 32];
    key[..domain.len()].copy_from_slice(domain);

    let mut result = vec![[0u8; 32]; DEPTH + 1];
    // result[0] = ZERO_HASH = [0; 32]
    for i in 1..=DEPTH {
        let mut hasher = blake3::Hasher::new_keyed(&key);
        hasher.update(&result[i - 1]);
        hasher.update(&result[i - 1]);
        let hash = hasher.finalize();
        result[i] = *hash.as_bytes();
    }
    result
}

fn format_hash(bytes: &[u8; 32]) -> String {
    let inner: Vec<String> = bytes.iter().map(|b| format!("0x{b:02x}")).collect();
    format!("kaspa_hashes::Hash::from_bytes([{}])", inner.join(", "))
}

fn main() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest_path = std::path::Path::new(&out_dir).join("empty_hashes_generated.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit.\n\n");

    for &(name, domain, collapsed) in KNOWN_HASHERS {
        let hashes = compute_empty_hashes(domain);
        code.push_str(&format!("impl SmtHasher for kaspa_hashes::{name} {{\n"));
        code.push_str(&format!("    type CollapsedHasher = kaspa_hashes::{collapsed};\n"));
        code.push_str("    const EMPTY_HASHES: [kaspa_hashes::Hash; DEPTH + 1] = [\n");
        for h in &hashes {
            code.push_str(&format!("        {},\n", format_hash(h)));
        }
        code.push_str("    ];\n");
        code.push_str("}\n\n");
    }

    std::fs::write(dest_path, code).unwrap();
    println!("cargo::rerun-if-changed=build.rs");
}
