#!/bin/bash
set -e

if [ "$1" = "--partial" ]; then

    echo "building wasm32-sdk"
    wasm-pack build --target web --out-name kaspa --out-dir web/kaspa --features wasm32-sdk
    echo "building wasm32-rpc"
    wasm-pack build --target web --out-name kaspa --out-dir web/kaspa-rpc --features wasm32-rpc

else

    echo "building wasm32-keygen"
    wasm-pack build --target web --out-name kaspa --out-dir web/kaspa-keygen --features wasm32-keygen
    echo "building wasm32-rpc"
    wasm-pack build --target web --out-name kaspa --out-dir web/kaspa-rpc --features wasm32-rpc
    echo "building wasm32-core"
    wasm-pack build --target web --out-name kaspa --out-dir web/kaspa-core --features wasm32-core
    echo "building wasm32-sdk"
    wasm-pack build --target web --out-name kaspa --out-dir web/kaspa --features wasm32-sdk

fi