pub mod client;
pub mod server;

pub mod convert;
pub mod ext;

// We have no control over the code generated by the tonic builder,
// so clippy is fully disabled here.
#[allow(clippy::all)]
pub mod protowire {
    tonic::include_proto!("protowire");
}
