#!/bin/bash

VENV_DIR="env"

if [ ! -d "$VENV_DIR" ]; then
    echo "Creating virtual environment in $VENV_DIR..."
    python3 -m venv $VENV_DIR
fi

echo "Activating virtual environment..."
source $VENV_DIR/bin/activate

if ! command -v maturin &> /dev/null; then
    echo "Maturin not found, installing..."
    pip install maturin
else
    echo "Maturin is already installed."
fi

echo "Running 'maturin develop --features py-sdk'..."
maturin develop --release --features py-sdk

echo "Script execution completed."
