[package]
name = "kaspa-wrpc-python"
description = "Kaspa wRPC Python client"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
py-sdk = [
    "pyo3/extension-module",
    "kaspa-addresses/py-sdk",
    "kaspa-rpc-core/py-sdk",
    "kaspa-wrpc-client/py-sdk",
]

[dependencies]
ahash.workspace = true
cfg-if.workspace = true
futures.workspace = true
kaspa-addresses.workspace = true
kaspa-consensus-core.workspace = true
kaspa-notify.workspace = true
kaspa-rpc-core.workspace = true
kaspa-rpc-macros.workspace = true
kaspa-wrpc-client.workspace = true
kaspa-python-macros.workspace = true
log.workspace = true
pyo3.workspace = true
pyo3-async-runtimes.workspace = true
serde_json.workspace = true
serde-pyobject.workspace = true
thiserror.workspace = true
workflow-core.workspace = true
workflow-log.workspace = true
workflow-rpc.workspace = true

[lints]
workspace = true
