[package]
name = "kaspa-wallet-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
async-trait.workspace = true
convert_case.workspace = true
futures.workspace = true
kaspa-wallet-core.workspace = true
kaspa-wrpc-client.workspace = true
pad.workspace = true
thiserror.workspace = true
workflow-core.workspace = true
workflow-dom.workspace = true
workflow-log.workspace = true
workflow-terminal.workspace = true